import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { useSelector } from 'react-redux';
import { useGetActiveMatchesQuery } from '../store/services/api';
import Page from '../components/Page';
import { useNavigate } from 'react-router-dom';
export default function Matches() {
    const navigate = useNavigate();
    const user = useSelector((s) => s.auth.user);
    const { data: matchesData, isLoading, refetch } = useGetActiveMatchesQuery(undefined, { skip: !user });
    if (!user) {
        return (_jsx(Page, { title: "Your Matches", children: _jsxs("div", { className: "glass rounded-2xl p-6 text-center", children: [_jsx("h3", { className: "text-lg font-semibold mb-2", children: "Please log in" }), _jsx("button", { onClick: () => navigate('/login'), className: "px-4 py-2 bg-brand-pink rounded-lg hover:bg-brand-pink/90 transition-colors", children: "Log In" })] }) }));
    }
    if (isLoading) {
        return (_jsx(Page, { title: "Your Matches", children: _jsxs("div", { className: "glass rounded-2xl p-6 text-center", children: [_jsx("div", { className: "w-8 h-8 border-2 border-brand-pink border-t-transparent rounded-full animate-spin mx-auto mb-4" }), _jsx("p", { className: "text-white/70", children: "Loading your matches..." })] }) }));
    }
    const matches = matchesData?.matches || [];
    return (_jsx(Page, { title: "Your Matches", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsx("div", { className: "glass rounded-2xl p-6 mb-6", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-white", children: "Your Matches" }), _jsxs("p", { className: "text-white/70", children: [matches.length, " ", matches.length === 1 ? 'match' : 'matches'] })] }), _jsx("button", { onClick: () => refetch(), className: "px-4 py-2 bg-white/10 rounded-lg hover:bg-white/20 transition-colors text-white", children: "Refresh" })] }) }), matches.length === 0 ? (_jsxs("div", { className: "glass rounded-2xl p-8 text-center", children: [_jsx("div", { className: "text-6xl mb-4", children: "\uD83D\uDC94" }), _jsx("h3", { className: "text-xl font-semibold mb-2", children: "No matches yet" }), _jsx("p", { className: "text-white/70 mb-6", children: "Start swiping to find your perfect matches!" }), _jsx("button", { onClick: () => navigate('/dating'), className: "px-6 py-3 bg-brand-pink rounded-lg hover:bg-brand-pink/90 transition-colors", children: "Start Swiping" })] })) : (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: matches.map((match, index) => (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: index * 0.1 }, className: "glass rounded-2xl p-6 hover:scale-105 transition-transform cursor-pointer", onClick: () => {
                            // For now, just show an alert. In a real app, this would open a chat
                            alert(`Chat with ${match.user.username} - Coming soon!`);
                        }, children: [_jsx("div", { className: "w-20 h-20 mx-auto mb-4 rounded-full overflow-hidden", children: match.user.photos && match.user.photos.length > 0 ? (_jsx("img", { src: match.user.photos[0], alt: match.user.username, className: "w-full h-full object-cover" })) : (_jsx("div", { className: "w-full h-full bg-gradient-to-br from-gray-700 to-gray-900 flex items-center justify-center", children: _jsx("span", { className: "text-2xl text-white/50", children: "\uD83D\uDC64" }) })) }), _jsxs("div", { className: "text-center mb-4", children: [_jsx("h3", { className: "text-lg font-semibold text-white mb-1", children: match.user.username }), match.user.age && (_jsxs("p", { className: "text-white/70 text-sm", children: [match.user.age, " years old"] })), match.user.bio && (_jsx("p", { className: "text-white/60 text-xs mt-2 line-clamp-2", children: match.user.bio }))] }), _jsxs("div", { className: "space-y-2 text-xs text-white/60", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Matched:" }), _jsx("span", { children: new Date(match.matchedAt).toLocaleDateString() })] }), match.hasMarket && (_jsx("div", { className: "bg-brand-pink/20 text-brand-pink text-center py-1 px-2 rounded", children: "Betting Market Available" }))] }), _jsxs("div", { className: "flex gap-2 mt-4", children: [_jsx("button", { onClick: (e) => {
                                            e.stopPropagation();
                                            alert('Chat feature coming soon!');
                                        }, className: "flex-1 px-3 py-2 bg-brand-pink rounded-lg hover:bg-brand-pink/90 transition-colors text-white text-sm", children: "\uD83D\uDCAC Chat" }), match.hasMarket && (_jsx("button", { onClick: (e) => {
                                            e.stopPropagation();
                                            navigate('/markets');
                                        }, className: "flex-1 px-3 py-2 bg-white/10 rounded-lg hover:bg-white/20 transition-colors text-white text-sm", children: "\uD83C\uDFAF Bet" }))] })] }, match.matchId))) })), _jsxs("div", { className: "mt-8 grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsxs("button", { onClick: () => navigate('/dating'), className: "glass rounded-xl p-4 hover:bg-white/5 transition-colors text-center", children: [_jsx("div", { className: "text-2xl mb-2", children: "\uD83D\uDC96" }), _jsx("div", { className: "font-medium text-white", children: "Find More Matches" }), _jsx("div", { className: "text-white/60 text-sm", children: "Keep swiping" })] }), _jsxs("button", { onClick: () => navigate('/profile'), className: "glass rounded-xl p-4 hover:bg-white/5 transition-colors text-center", children: [_jsx("div", { className: "text-2xl mb-2", children: "\uD83D\uDC64" }), _jsx("div", { className: "font-medium text-white", children: "Edit Profile" }), _jsx("div", { className: "text-white/60 text-sm", children: "Update your info" })] }), _jsxs("button", { onClick: () => navigate('/markets'), className: "glass rounded-xl p-4 hover:bg-white/5 transition-colors text-center", children: [_jsx("div", { className: "text-2xl mb-2", children: "\uD83C\uDFAF" }), _jsx("div", { className: "font-medium text-white", children: "Browse Markets" }), _jsx("div", { className: "text-white/60 text-sm", children: "Place some bets" })] })] })] }) }));
}
